---
booktitle: Proceedings of the NIPS 2014 Workshop on High-energy Physics and Machine
  Learning
shortname: HEPML
volume: 42
year: '2014'
start: 2014-12-13
end: 2014-12-13
published: 2015-08-27
sections:
- name: preface
  title: Preface
- name: default
  title: Accepted Papers
layout: proceedings
series: Proceedings of Machine Learning Research
id: HEPML14
month: 0
abstract: ''
tex_title: 
title: Proceedings of Machine Learning Research
cycles: false
editor:
- given: Glen
  family: Cowan
- given: Cécile
  family: Germain
- given: Isabelle
  family: Guyon
- given: Balázs
  family: Kégl
- given: David
  family: Rousseau
description: |
  Proceedings of the NIPS 2014 Workshop on High-energy Physics and Machine Learning
    Held in Montreal, Canada on 13 December 2014

  Published as Volume 42 by the Proceedings of Machine Learning Research on 27 August 2015.

  Volume Edited by:
    Glen Cowan
    Cécile Germain
    Isabelle Guyon
    Balázs Kégl
    David Rousseau

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 13 Dec
url: http://proceedings.mlr.press
baseurl: "/v42"
twitter_username: mlresearch
github_username: mlresearch
markdown: kramdown
permalink: "/:title.html"
github:
  edit: true
  repository: v42
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: NIPS 2014 Workshop on High-energy Physics and Machine Learning
  url: https://sites.google.com/site/hepml14/home
  location: Montreal, Canada
  dates:
  - 2014-12-13
analytics:
  google:
    tracking_id: UA-92432422-1
# Site settings
# Auto generated from v42.bib
